#! /usr/bin/env zsh

# Remove command lines from the history list when the first character on the
# line is a space, or when one of the expanded aliases contains a leading space
setopt histignorespace

# Do not enter command lines into the history list if they are duplicates of the
# previous event.
setopt histignorealldups
