#! /usr/bin/env zsh

#	Shell settings
#	------------------------------------------------------------------------
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export GPG_TTY=$(tty)

export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
export SAVEHIST=1000000000

export EDITOR='vim'
export GIT_EDITOR='vim'

export GIT_RADAR_FETCH_TIME=30
export LESS=eFRX

export COMPOSER_ALLOW_SUPERUSER=1
