#! /usr/bin/env zsh

#	-----------------------------------------
#		MAKE TERMINAL BETTER
#	-----------------------------------------
alias ls='ls --grid'
alias l='ls --long --header'
alias la='ls --long --all --header'
alias laz='ls --long --all --header --context'
alias lao='ls --long --all --header --octal-permissions'
alias cp='nocorrect cp -iv'														# Preferred 'cp' implentation
alias mv='nocorrect mv -iv'														# Preferred 'mv' implentation
alias mkdir='nocorrect mkdir -pv'												# Preferred 'mkdir' implentation
alias rm='rm -v'																# Preferred 'rm' implentation
alias mkcd='take'																# Replaces old zsh function for making and cd to the directory

alias cd..='cd ../'																# Go back 1 directory level (for fast typers)
alias ..='cd ../'																# Go back 1 directory level
alias ...='cd ../../'															# Go back 2 directory levelssy
alias path='echo -e ${PATH//:/\\n}'												# Echo all executable Paths
alias fpath='echo -e ${FPATH//:/\\n}'											# Echo all zsh function Paths
alias completions='echo $fpath | sed -e "s/ /\n/g" | sort'						# Echo all zsh funcrion Paths in a sorted list

alias df="df -h -x overlay -x tmpfs"											# Hide overlay and tmpfs from df. And show sizes as human readable
alias du="du -ch"																# Show sizes as human readable and show a grand total
alias du1="du -chd1"															# Shortcut to get the size of the current directory and it's imediate children
function ps() {																	# Make ps always show the full command
	echo "$(/usr/bin/ps $@)"
}

alias reload="exec zsh"															# Reload zshrc
alias ssh0="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"	# Quick SSH without messing up your known hosts file
alias ygui="true"																# I do not use this alias anymore, but it is so ingrained in my muscle memory that I changed it to a no-op

#	---------------------------------------
#		MAKE GIT GREAT AGAIN
#	---------------------------------------
alias s='git status'
alias add='git add'
alias commit="git commit"


#	---------------------------------------
#		MAKE NETWORKING GREAT AGAIN
#	---------------------------------------
alias myip='curl -4 icanhazip.com; curl -6 icanhazip.com'						# Get my public facing IP Address
alias ips="ip a s | grep 'inet ' | awk '{print \$2}' | cut -f1 -d'/' | sort"	# Get all my IPv4 Addresses
alias ip6s='ip6 a s | grep '\''inet6 '\'' | grep -v '\''fe80::'\'' | awk '\''{print $2}'\'' | cut -f1 -d'\''/'\'' | sort' # Get all my IPv6 Addresses
alias ip4="ip -4"																# Shortcut for only querying IPv4
alias ip6="ip -6"																# Shortcut for only querying IPv6
alias dig4="dig -4"																# Shortcut for only querying IPv4
alias dig6="dig -6"																# Shortcut for only querying IPv6

#	---------------------------------------
#		MAKE DOCKER GREAT AGAIN
#	---------------------------------------

alias dk='docker kill $(docker ps -q)'											# Kill all containers (be careful)
function dc() {																	# Docker-compose shortcut
	if [ -x "$(command -v docker-compose)" ]; then
		docker-compose $@
	else
		docker compose $@
	fi
}

#	---------------------------------------
#		MAKE KUBECTX GREAT AGAIN
#	---------------------------------------

alias kctx='kubectx'
alias kns='kubens'

#	---------------------------------------
#		MAKE MACOS GREAT AGAIN
#	---------------------------------------
alias flushDNS='sudo killall -HUP mDNSResponder'								# Flush out the DNS Cache (macOS)
alias cleanupDS="find . -type f -name '*.DS_Store' -ls -delete"					# Recursively delete .DS_Store files
