#! /usr/bin/env zsh

# Generate lockfile for all platforms
alias tfpl='terraform providers lock -platform=linux_arm64 -platform=linux_amd64 -platform=darwin_amd64 -platform=darwin_arm64 -platform=windows_amd64'
