#!/usr/bin/env zsh

function command_exists() {
	command -v "$@" >/dev/null 2>&1
}

function decodeCertificate() {
	if [[ "$(uname -s)" == "Linux" ]]; then
		alias pbpaste="xclip -selection clipboard -o"
	fi

	if ! command_exists step; then
		echo "step binary doesn't exist"
		return
	fi

	local file="$1"
	shift 2>/dev/null

	if [ -z "$file" ]; then
		pbpaste | sed 's/^[[:space:]]*//' | step certificate inspect "$@"
	else
		sed 's/^[[:space:]]*//' "$file" | step certificate inspect "$@"
	fi
}

function decodeB64Certificate() {
	if [[ "$(uname -s)" == "Linux" ]]; then
		alias pbpaste="xclip -selection clipboard -o"
	fi

	# Check if the step binary exists
	if ! command_exists step; then
		echo "step binary doesn't exist"
		return
	fi

	pbpaste | base64 -d | step certificate inspect "$@"
}

unset command_exists
